### PR TITLE
Flow plugin - initial submission

### PR DESCRIPTION
**Pull request by IMHarris**
Hi Dan,

First time contributing to a GitHub project, so I hope I'm doing this correctly.  Here's the flow addin.  I think version 1 is ready to go.

Documentation is [here](https://github.com/IMHarris/SIP_plugins/wiki).

Happy to answer any questions.

Regards,

Ian

### CODE REVIEW

**Comment by Dan-in-CA** [comment]
Thanks Ian,
Your contribution is greatly appreciated. 
It looks like your pull request can be merged without any problems. I will look it over first and then merge it shortly.
Dan

**Comment by Dan-in-CA** [comment]
The only other thing that needs to happen is to add the name and description of your plugin to the README.md file on the plugins repo so it will show up for selection in the Plugin manager.
I will take care of that.
Dan

**Comment by Dan-in-CA** [comment]
There was a problem installing the plugin. The flowhelpers folder does not get created by the pjlugin manager, This causes an error.
I will work on a fix. It may take a couple of hours.
Dan

**Comment by Dan-in-CA** [comment]
I created the flowhelpers folder manually and got the plugin to install. When SIP restarted there was a divide by zero error raised.
I'm not sure how serous the error is because the plugin seems to load and run. It may have something to do with the fact that I don't have a sensor installed?

**Comment by IMHarris** [comment]
Thanks for helping get all this sorted out.  I have a hunch where the /0 is coming from.  Looking at it now.

**Comment by Dan-in-CA** [comment]
By the way You did a great job with the docs.
One suggestion: It might be a good idea to mention under requirements that I2C must be enabled on the Pi.

I looked for a way to download a folder from GitHub but it looks like the best way to go is to put flowhelpers.py and arduinocode.txt into the SIP/plugins folder. You could even place arduinocode.txt in the docs wiki and users could get it from there which would probably be easier for them.
I tried putting flowhelpers.py in the plugins folder and commented out line 7 of flow.py and it seemed to work OK. This will also require minor edits to the manifest file.

**Pull request merged**
