### PR TITLE
relay_board plugin: Add support for ODROID-C2

### PR DESCRIPTION
**Pull request by egisz**
I've added support for ODROID-C2 in relay_board plugin
Tested, and works fine so far.
To avoid code duplicates, I've reused procedures (set_pin_mode_output, set_pin_high, set_pin_low), which  I added to SIP/gpio_pins.py
They are added in pull request : https://github.com/Dan-in-CA/SIP/pull/196

In case pull request is not accepted, then I'll have to copy same procedures to plugin...

### CODE REVIEW

**Comment by Dan-in-CA** [comment]
Is this new? It has a date of Oct 13, 2017.
It looks like the code is Python3 compatible but the Odroid-C2 branch of SIP is still 2 years old.

GitHub says that This branch has conflicts that must be resolved

Dan

**Comment by egisz** [comment]
Hi, Dan,

Yes, that was old PR, I did not noticed it is still open. You decided then that you don't want to merge Odroid-C2 branch into master (SIP project) and also left this PR unmerged.

I still use Odroid-C2 board and decided to update to current SIP version. It is running since yesterday just fine.

In [SIP Wiki](https://github.com/Dan-in-CA/SIP/wiki), there are [instructions ](https://github.com/Dan-in-CA/SIP/wiki/Installation-(Odroid-C2)) how to install it on C2, so I guess we can can close this PR and leave it as it is.

OR I could fix conflicts if you are willing to merge it?

**Comment by Dan-in-CA** [comment]
Let's give it a try.
Go ahead and fix the conflicts.

**Comment by Dan-in-CA** [comment]
Cleaning up old requests.

**Pull request closed without merging**
