### PR TITLE
Flow plugin SMS and Voice notifications support.

### PR DESCRIPTION
**Pull request by IMHarris**
Added support to Flow plugin for SMS and Voice notifications.

### CODE REVIEW

**Comment by Dan-in-CA** [comment]
Fantastic!
Thanks for the continued work on this.
Dan

**Comment by IMHarris** [comment]
This has been fun.  :)

One more pull request on the way.  A new plugin to support the [Plivo](https://www.plivo.com) messaging service - coming shortly.  I've been using this service for several years. The cost is pretty low and the service and support have been great.

Hope you had a great Thanksgiving.

Ian

**Comment by Dan-in-CA** [comment]
Hi Ian,
The Plivo plugin sounds interesting. Looking forward to that.

I recently found an article that describes an algorithm that can use soil moisture sensors to control the amount of irrigation water applied. They claim that it can provide optimal soil moisture using half the water. Your flow plugin will be extremely useful in testing a SIP implementation. It requires that SIP can automatically read remote sensors and I have the hardware and software almost ready to go using a new node-RED plugin and ESP32 boards.

We had a wonderful thanks giving and I hope you did as well.

Dan

**Comment by IMHarris** [comment]
I had been looking at heading towards moisture sensors next as well.  I'm excited to see where you've gone with it.  Which sensors have you selected?

Thanksgiving was really great here too.  Normally, we host, but this year our family went to my sister-in-law's and it was lovely.

**Comment by IMHarris** [comment]
Hey Dan,

I was looking at the new work you posted around moisture sensors.  Looking
good.  Any recommendations on hardware/software on the sensor side of the
system?  You mentioned a while back you were looking at Irrometer sensors.
Looking for your thoughts on what you're using to collect the sensor data
and send along to MQTT.

**Comment by Dan-in-CA** [comment]
This is my second growing season with automatic moisture sensor control of a small corn patch.
I am still tweaking the logic.

The system uses 2 Irrometer watermark sensors. 1 at t depth of 1 foot and 1 at a depth of 2 feet plus a temperature sensor at a depth of 18 inches. The sensor readings are sent via MQTT over wifi using an ESP32 powered by a solar panel.

Getting the best settings is a bit tricky as it involves the soil's water penetration rate with affects the time it takes for the sensors to respond to an irrigation event.

**Comment by IMHarris** [comment]
Very helpful. Thanks Dan. IanSent from my mobile phone.On Jul 14, 2024, at 10:18 AM, Dan ***@***.***> wrote:﻿
This is my second growing season with automatic moisture sensor control of a small corn patch.
I am still tweaking the logic.
The system uses 2 Irrometer watermark sensors. 1 at t depth of 1 foot and 1 at a depth of 2 feet plus a temperature sensor at a depth of 18 inches. The sensor readings are sent via MQTT over wifi using an ESP32 powered by a solar panel.
Getting the best settings is a bit tricky as it involves the soil's water penetration rate with affects the time it takes for the sensors to respond to an irrigation event.

**Pull request merged**
