### PR TITLE
Use OpenWeatherMap for Water Level and Weather Adjustment.

### PR DESCRIPTION
**Pull request by airsoftsoldrecn9**
Updated Weather Adjust and Weather Level Adjust to use OpenWeatherMap. Wunderground API is no more.

The idea is to mimic the same functionality as before. I create a weighted moving average (metrics mostly based on rainfall, but other factors include: temperature, humidity and wind. Outside general weather conditions are given percentage weights. All of this combined will adjust the watering time percentage accordingly. Data is stored in JSON files, labeled by date in weather_current and weather_level_history. Please review and adjust the settings in weather_adj.json, weather_level_adj.json and weather_decipher.json. (This is highly summarized and quite possibly naive. It has been tested somewhat, but I have not had time to really review my code for proper functionality. Please forgive me if there are mistakes in my logic here.)

Added a few additional options in addition to the original set which includes a geolocation, and some useful adjustment parameters including "rainfall_per_day", and "time_zone". Plan to add more as this becomes refined.

Data_Example directory contains some example json config files (I think it should be included in the Plugins, at least so others have something out of the box to start with).

### CODE REVIEW

**Comment by Dan-in-CA** [comment]
Thank you!
I accepted the merge request without testing.
This is something many users have been waiting for.
I will post an announcement on the SIP forum and include a link here for feedback.

**Comment by airsoftsoldrecn9** [comment]
Np, sounds good. :)

**Comment by FulvioSpelta** [comment]
Hi all,
today (25may) I've installed the updated plugin using SIP plugin manager and configured with my location (checked using OW website) and my api key. After rester the plug status is:
`Weather-base water level encountered error:
Traceback (most recent call last):
  File "/home/pi/SIP/plugins/weather_level_adj.py", line 97, in run
    today = today_info(self, options)
  File "/home/pi/SIP/plugins/weather_level_adj.py", line 313, in today_info
    if name in os.listdir(path):
OSError: [Errno 2] No such file or directory: './data/weather_level_history'
`

image

**Comment by FulvioSpelta** [comment]
I've manually created the directory but nothing changed:
image

thx

**Comment by airsoftsoldrecn9** [comment]
You must remove the old files and use the new files within the directory
"data". They are added in the plugins as an example. From there, you can
modify the settings as you see fit.

**Comment by FulvioSpelta** [comment]
> You must remove the old files and use the new files within the directory "data". They are added in the plugins as an example. From there, you can modify the settings as you see fit.

**Reply to the post**
Sorry I can't understand your reply.: the plugin is installed and it is running properly. No further action seems needed.

**Comment**
My post aim to share my installation experience (first installation at all: there aren't any "old files") in order to let you know that, using "plugin manager", the plugin seems not able to run "play&play" due to the 2 problems reported.

I've used plugin manager in order to test the just accepted PR as the simplest way and to provide a contribution to the testing.

**Comment by bterry35** [comment]
Hello all, I just set up a pi and installed SIP.  Waiting for a relay board from Amazon,  to complete the setup.  I installed this plugin, created the weather_level_history directory, and copied weather_decipher.json.  The plugin is working.  I now have "Plugin adjustments: 14% " on the home screen.  So this may be a stupid question, but does this mean 14% less than my time setting, or 14% of my time setting?  Thank you.

**Comment by Dan-in-CA** [comment]
That would be 14% of your time setting. It will deliver 14% of the scheduled water.

**Comment by airsoftsoldrecn9** [comment]
FulvioSpelta,

May I have a screenshot of your directory structure? The directory
weather_level_history must exist (seems to be missing). In the meantime, I
will make fixes to automatically create these directories.

**Comment by bterry35** [comment]
Thanks @Dan-in-CA  for your quick response, and this awesome project.

**Comment by FulvioSpelta** [comment]
> FulvioSpelta, May I have a screenshot of your directory structure? The directory weather_level_history must exist (seems to be missing). In the meantime, I will make fixes to automatically create these directories.

HI, the directory structure is already present in my post; the weather_level_history directory was missing after the installation (using plugin manager) of the plugin.

My SIP system is: `Software version: 3.2.999 (2015-01-09)`

**Comment by MrCmonster** [comment]
I have the new plugin mostly working, but I have a little bug. If I try to use the full name of where I live “Pueblo West, US” the plugin is changing it to just Pueblo which is a few miles away. I’m able to see Pueblo West, US on openweather at https://openweathermap.org/city/5435477
Any ideas? Thanks.

**Comment by airsoftsoldrecn9** [comment]
Good catch. I am probably not looking up the full phrase "Pueblo West" for
the location ID, but rather just parsing and appending with the first
string "Pueblo". Will need to check the URI with that location, to be sure.

**Comment by bterryUFG** [comment]
@MrCmonster @airsoftsoldrecn9 I noticed the same issue with my city "Yuba City".  I was able to get it working by using my zip code.

**Comment by MrCmonster** [comment]
I tried with my zip code, 81007, but it changed it to Pueblo as well.

**Comment by FulvioSpelta** [comment]
Hi @airsoftsoldrecn9 just a cosmetic hints: in the status log (plugin setup window) could be noce to insert a reference date/time in order to know when the log was produced and what days have been analyzed.
image

Thans again

**Comment by airsoftsoldrecn9** [comment]
Ok, I will add that to the next update.

**Comment by dannyakarudy** [comment]
So i copied over the new files and set up everything.  when I go to look at the Current temp in C it is incorrect.  When I looked ad the code for today and followed how the URL is built and manually enter it into a browser I get the 'correct' current temp in C.  I have no idea why it isn't working.

**Comment by dannyakarudy** [comment]
> So i copied over the new files and set up everything. when I go to look at the Current temp in C it is incorrect. When I looked ad the code for today and followed how the URL is built and manually enter it into a browser I get the 'correct' current temp in C. I have no idea why it isn't working.

For anyone else that has the problem (you probably do and may not have noticed) I solved the issue by changing like 277 of weather_level_adj.py from:
    history = curr_conditions
to
    history = curr_conditions.copy()

What I believe the issue here is that the curr_condition argument passed to the history function is 'today'.  Inside the history function the history variable (which is only set as a reference to curr-conditions) performs operations on history, which in turn affects curr_conditions which is really 'today'.

See the following link for possibly a better explantion then I'm making...

[](https://thomas-cokelaer.info/blog/2017/12/python-how-to-copy-a-list/)

**Comment by dannyakarudy** [comment]
https://thomas-cokelaer.info/blog/2017/12/python-how-to-copy-a-list/

**Comment by airsoftsoldrecn9** [comment]
I will add this to my fix list.

**Comment by dannyakarudy** [comment]
Also not sure timezone option needs to be listed… it looks as though there is a timezone adjustment variable returned by openweather…


{"coord":{"lon":-119.28,"lat":46.28},"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"01n"}],"base":"stations","main":{"temp":295.69,"pressure":1018,"humidity":68,"temp_min":291.48,"temp_max":298.71},"visibility":16093,"wind":{"speed":2.1,"deg":20},"clouds":{"all":1},"dt":1560316409,"sys":{"type":1,"id":5409,"message":0.0083,"country":"US","sunrise":1560254705,"sunset":1560311317},"timezone":-25200,"id":5808276,"name":"Richland","cod":200}


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by airsoftsoldrecn9** [comment]
You are correct, I actually noticed this and already made some adjustments
to use that key instead. I also reference the location specified in the
system settings to determine locale for the open weather map data.

**Comment by dannyakarudy** [comment]
I would just caution folks to use the open weather site to narrow down their location... For example if I just use my zip code there is an issue as it turns 3 different options... I found if I use 99352,US it returns appropriately...

On Jun 11, 2019 11:10 PM, airsoftsoldrecn9 <notifications@github.com> wrote:
You are correct, I actually noticed this and already made some adjustments
to use that key instead. I also reference the location specified in the
system settings to determine locale for the open weather map data.

**Comment by airsoftsoldrecn9** [comment]
Would you mind referencing those locations so I could test (Is this
Richland, WA)?

**Comment by dannyakarudy** [comment]
[cid:image003.png@01D520FC.D64F3420]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by dannyakarudy** [comment]
In addition the history function is kind of messed up.  As opposed to looking at the last 5 days of history it looks at the last 5 files…  It prunes any thereafter… So what you end up with is it looking at the very first 5 history files ever created… Probably not what was intended.

I solved that issue by removing the references to count in the function.  I tested the modification by placing a file with a date older than 5 days and it was not included in the calculation and was pruned from the directory.

Best I can tell what this will do is every hour when the program updates it will create a new history file.  So 24 history files per day * 5 days it will be 120 or so history files created.

This is what would be required if you want to average the temperature throughout the day for 5 days.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by FulvioSpelta** [comment]
> In addition the history function is kind of messed up. As opposed to looking at the last 5 days of history it looks at the last 5 files… It prunes any thereafter… So what you end up with is it looking at the very first 5 history files ever created… Probably not what was intended. I solved that issue by removing the references to count in the function. I tested the modification by placing a file with a date older than 5 days and it was not included in the calculation and was pruned from the directory. Best I can tell what this will do is every hour when the program updates it will create a new history file. So 24 history files per day * 5 days it will be 120 or so history files created. This is what would be required if you want to average the temperature throughout the day for 5 days. 

Hi, do you have any news ? I've deleted any references to "!count" but now the history files are never deleted and looking to water budget adjust it seems is not reliable.

I don't know python so it's hard for me to do correction to the code, but i can help in test.

Thanks

**Comment by FulvioSpelta** [comment]
> In addition the history function is kind of messed up. As opposed to looking at the last 5 days of history it looks at the last 5 files… It prunes any thereafter… So what you end up with is it looking at the very first 5 history files ever created… Probably not what was intended. I solved that issue by removing the references to count in the function. I tested the modification by placing a file with a date older than 5 days and it was not included in the calculation and was pruned from the directory. Best I can tell what this will do is every hour when the program updates it will create a new history file. So 24 history files per day * 5 days it will be 120 or so history files created. This is what would be required if you want to average the temperature throughout the day for 5 days. 

Do you think to release a push request ?
Thanks

**Comment by dannyakarudy** [comment]
There will be 24*5 or 120 files created before any are deleted.... A new history file is created every hour.

On Jun 17, 2019 11:42 PM, FulvioSpelta <notifications@github.com> wrote:

In addition the history function is kind of messed up. As opposed to looking at the last 5 days of history it looks at the last 5 files… It prunes any thereafter… So what you end up with is it looking at the very first 5 history files ever created… Probably not what was intended. I solved that issue by removing the references to count in the function. I tested the modification by placing a file with a date older than 5 days and it was not included in the calculation and was pruned from the directory. Best I can tell what this will do is every hour when the program updates it will create a new history file. So 24 history files per day * 5 days it will be 120 or so history files created. This is what would be required if you want to average the temperature throughout the day for 5 days.

Hi, do you have any news ? I've deleted any references to "!count" but now the history files are never deleted and looking to water budget adjust it seems is not reliable.

I don't know python so it's hard for me to do correction to the code, but i can help in test.

Thanks

**Comment by daveethier** [comment]
Getting the following error when using the Weather-based Water Level plug-in. Also using the location of 55378,US.

Any ideas?

Weather-base water level encountered error:
Traceback (most recent call last):
  File "/home/pi/SIP/plugins/weather_level_adj.py", line 99, in run
    history = history_info(self, today, options)
  File "/home/pi/SIP/plugins/weather_level_adj.py", line 286, in history_info
    thisdate_time = datetime.datetime(int(tmp[0]), int(tmp[1]), int(tmp[2]), int(tmp[3]), int(tmp[4]))
IndexError: list index out of range

**Comment by dannyakarudy** [comment]
I have to ask… Did you get your API key and all that?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by daveethier** [comment]
Always good to verify but yes I do have my API key. Its interesting I am getting some results in the Data directory such as History, forecast 5 day, conditions when I do a Submit from the Weather-based Water Level plugin. So I know the API is working. Seems like the issue is around parsing the results.



________________________________

**Comment by dannyakarudy** [comment]
Have you looked at the files to see what is in them?

On Jul 21, 2019 3:40 PM, daveethier <notifications@github.com> wrote:
Always good to verify but yes I do have my API key. Its interesting I am getting some results in the Data directory such as History, forecast 5 day, conditions when I do a Submit from the Weather-based Water Level plugin. So I know the API is working. Seems like the issue is around parsing the results.



________________________________

**Pull request merged**
