### PR TITLE
Flow: /0 error

### PR DESCRIPTION
**Pull request by IMHarris**
Hi Dan,

Sorry for the bother.  Apparently, I didn't test well the scenario where the settings had not been fully set up.

Try out with these updates, please.

Ian

### CODE REVIEW

**Comment by Dan-in-CA** [comment]
No bother, I have had my share of bugs also. It now loads without any error.

We still need to fix the problem of the flowhelpers folder not being created. 
I will tackle that problem tomorrow and let you know what changes I make. You have done great work on this and I am sure it will be a popular plugin. I plan to use it myself as there are about to be mandatory water use restrictions where I live.

Dan

**Comment by IMHarris** [comment]
Thanks Dan.  I'm taking the message that you're planning on using the plugin yourself as a high compliment.  :)

And, thanks for helping to accomodate the file structure.

I'm excited to see the plugin working out in the wild!

Ian

**Comment by Dan-in-CA** [comment]
I am working on modifying the plugin manager to create the needed sub-directory. that looks like the best solution and may be useful for future plugins. 
It will require users to have an updated version of SIP in order to install your plugin.
I will let you know more details later as it may take a while to get it working and test.

**Comment by Dan-in-CA** [comment]
OK. The plugin manager has been updated to create the flowhelpers sub-directory for your plugin.
Users will need to be running SIP version 4.1.46 or later in order for this to work. Or they can install an updated version of the plugin_manager from the plugins list..

You should probably add the SIP version to the requirements in your docs.

**Comment by Dan-in-CA** [comment]
I tested with a fresh install of SIP, installed your plugin with no errors and it seems to be working properly. 
I have some flow sensors and I will be working to install one in the next week or so.
Thanks again for your work on this.
Dan

**Comment by IMHarris** [comment]
Thanks Dan. I'll update the docs. Looking forward to hearing how it goes with you.

**Pull request merged**
